export const dotenv = {
  APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  WS_URL: process.env.NEXT_PUBLIC_RPC_URL as string,
  RPC_URL: process.env.NEXT_PUBLIC_RPC_HTTP as string,
  REALXMARKET_GRAPHQL_URL: process.env.NEXT_PUBLIC_REALXMARKET_GRAPHQL_API_URL,
  XCAV_AWS_REGION: process.env.NEXT_PUBLIC_AWS_REGION,
  AWS_S3_ACCESS_KEY: process.env.XCAV_AWS_S3_ACCESS_KEY,
  AWS_S3_SECRET_ACCESS_KEY: process.env.XCAV_AWS_S3_SECRET_ACCESS_KEY,
  AWS_S3_BUCKET_NAME: process.env.XCAV_AWS_S3_BUCKET_NAME,
  AWS_DYNAMODB_TABLE_NAME: process.env.XCAV_AWS_DYNAMODB_TABLE_NAME,
  AWS_ACCESS_KEY: process.env.XCAV_AWS_ACCESS_KEY,
  AWS_SECRET_ACCESS_KEY: process.env.XCAV_AWS_SECRET_KEY
};
