import { Property } from '@/types';

export const properties: Property[] = [
  {
    property_name: 'Plot 1 - Hertford Rise',
    id: '1',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop1-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 2 - Hertford Rise',
    id: '2',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop2-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 10 - High Rise',
    id: '3',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop4-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 11 - High Rise',
    id: '4',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop3-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 6 - Lime House',
    id: '5',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop6-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 6 - Lime House',
    id: '6',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop5-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  }
];
export const ad_properties: Property[] = [
  {
    property_name: 'Plot 1 - Hertford Rise',
    id: '1',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop1-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 2 - Hertford Rise',
    id: '2',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop2-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 10 - High Rise',
    id: '3',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop4-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  },
  {
    property_name: 'Plot 11 - High Rise',
    id: '4',
    address_street: 'The Avenue',
    address_town_city: 'Hertford',
    post_code: 'SG23 5TH',
    description: '2 bed apartment overlooking the river with balcony',
    area: '100sqm',
    quality: 'High',
    property_type: 'Flat',
    no_of_Bedrooms: 1,
    outdoor_space: 'None',
    construction_date: 'May2023',
    number_of_bathrooms: 1,
    Off_street_parking: '1 Space',
    floor_Plan: 'FloorPlanProperty-1.pdf',
    sales_agreement: 'PropertySaleAgreement.PDF',
    property_image: '/images/properties/prop3-1.jpg',
    images: [
      '/images/properties/prop1-2.jpg',
      '/images/properties/prop1-3.jpg',
      '/images/properties/prop1-4.jpg'
    ],
    property_price: '£250,000',
    estimated_rental_income: '£1200 pcm',
    property_development_Code: '4564SXZ1',
    planning_permission_Code: '3/22/1700/HH1',
    local_authority: 'East Herts',
    title_deed_number: '17646cnnn1',
    map: 'https://goo.gl/maps/RGi2riXVwnbPY4zQ6'
  }
];
